### ISSUE TITLE
Reasons to not use Pagerduty's go-pagerduty client

### ISSUE THREAD

**Issue by jufemaiz** [terraform-providers/terraform-provider-pagerduty#62]
### Affected Resource(s)
All

### Important Factoids
terraform-provider-pagerduty currently makes use of a go-pagerduty client from heimweh (ref: https://github.com/heimweh/go-pagerduty ), however there is a different official Pagerduty go-pagerduty client (ref: https://github.com/PagerDuty/go-pagerduty).

* Is there an official reason to use an unofficial client where an official one exists?
* If so, could we please make not in the README.md?
* If not, is it worthwhile investigating the requirements to migrate to the officially released client for a v0.2.0 release?

**Comment by heimweh** [comment]
Hi @jufemaiz, thank you for opening this issue.

The original implementation of the PagerDuty provider was actually written using the https://github.com/PagerDuty/go-pagerduty client.

The reasoning behind the change to https://github.com/heimweh/go-pagerduty was primarily because the official client library was pretty much stale at that point, contained some critical bugs and inconsistencies that made it very difficult to work with and was a blocker for the provider, so I opted for creating a dedicated Go client library just meant for the Terraform provider. I did try to reach out to PagerDuty about this and I've also provided some bug fixes/enhancements of which some got merged, but some were left hanging for unknown reasons.

If the state of the official client library changes, 
I'd be more than happy to switch back to using that client library :)

Hope this helps, and if you have any further questions just let me know :)

**Comment by jufemaiz** [comment]
Hi @heimweh,
thanks for the response! Good to know the backstory and the reasoning for a non-official client.

I've asked the question of them too (because realistically if they're ceasing support on it they may as well either direct people to the other one or at a minimum note that there will be no continued support).

Cheers, Joel

**Comment by jufemaiz** [comment]
As an update @heimweh, I got in touch with the support team. Their feedback was as follows:

> At the beginning of this month, we granted access in the repository to the original authors of the library and notified them. They themselves had also asked us about it, and about possibly helping, because unfortunately we have not been able to allocate internal engineering resources to the maintenance of it.
> 
> If, however, there are any issues in particular that are major blockers for usage, or pull requests that resolve them, I would be glad to put in the request for their prioritization.
