### ISSUE TITLE
html_url attribute on pagerduty_service_integration is not the Integration URL

### ISSUE THREAD

**Issue by jniesen** [terraform-providers/terraform-provider-pagerduty#76]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

```
> terraform -v
Terraform v0.11.4
+ provider.pagerduty v1.0.0
+ provider.template v1.0.0
```

### Affected Resource(s)

- pagerduty_service_integration

### Terraform Configuration Files
```hcl
resource "pagerduty_service_integration" "prod_splunk" {
  name            = "${data.pagerduty_vendor.splunk.name}"
  service         = "${pagerduty_service.art_prod.id}"
  vendor          = "${data.pagerduty_vendor.splunk.id}"
  integration_key = "[redacted]"
}

output "prod_splunk" {
  value = "${pagerduty_service_integration.prod_splunk.html_url}"
}
```

### Expected Behavior

Accodring to the [docs](https://www.terraform.io/docs/providers/pagerduty/r/service_integration.html#html_url):
> html_url - Configure your events to send webhooks to this endpoint. This is described as Integration URL in some Pagerduty documentation. 

The `prod_splunk` output should've contained a value like `https://events.pagerduty.com/integration/[redacted_key]/enqueue`

### Actual Behavior

The `prod_splunk` output contained a value like `https://dealer.pagerduty.com/services/[redacted]/integrations/[redacted]`.

Visiting this url takes me to the page where I can see the actual `integration_url`.

**Comment by jkrol2** [comment]
Experiencing the same issue. `html_url` returns the url to the page with integration details

**Comment by cwar** [comment]
Yeah I think this is a problem with the Pagerduty API as well because the API doesn't seem to return the `integration_url`. You should be able to construct `integration_url` with the interpolation `https://events.pagerduty.com/integration/${pagerduty_service_integration.slack.integration_key}/enqueue`. 

Not sure if that is helpful at all, but outside of hardcoding this interpolation within the terraform module I think this is the best we'll get until Pagerduty updates their API to return the integration URL (if they are even willing to do that).

The docs do need to be updated though, because this is misleading.
